name: test
on: [push, pull_request]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - run: npm ci --ignore-scripts --no-audit
  lint-js:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - run: npm ci --no-audit
      - run: npm run lint:js
  lint-css:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - run: npm ci --no-audit
      - run: npm run lint:css
  lint-webext:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: freaktechnik/web-ext-lint@v1
